lightgbm:
  objective: regression
  metric: rmse
  num_leaves: 31
  learning_rate: 0.05
  n_estimators: 300
  min_data_in_leaf: 20
  subsample: 0.9
  colsample_bytree: 0.9
  n_jobs: -1
quantile:
  enabled: true
  alpha_values: [0.1, 0.5, 0.9]
  n_estimators: 200
