# Global training configuration
random_state: 42
test_size: 0.2
n_jobs: 4
log1p_target: true
mlflow_tracking_uri: mlruns
experiment_name: reddit_upvotes
figures_dir: reports/figures
html_dir: reports/html
artifacts_dir: artifacts
quantiles: [0.1, 0.5, 0.9]
